Repository RocketSurgeonsGuild/Testing, pull requests merged in 2024-03, with the labels that each got.

#1136 feature: AutoFixture Source Generator
  Directory.Packages.props
  Readme.md
  Testing.sln
  src/Testing.AutoFixtures/AutoFixtureAttribute.cs
  src/Testing.AutoFixtures/AutoTestFixtureBuilderGenerator.cs
  src/Testing.AutoFixtures/BuilderExtensions.cs
  src/Testing.AutoFixtures/BuilderInterface.cs
  src/Testing.AutoFixtures/FixtureWithMethods.cs
  src/Testing.AutoFixtures/Methods.cs
  src/Testing.AutoFixtures/Properties/launchSettings.json
  src/Testing.AutoFixtures/PublicAPI.Shipped.txt
  src/Testing.AutoFixtures/PublicAPI.Unshipped.txt
  src/Testing.AutoFixtures/README.md
  src/Testing.AutoFixtures/Rocket.Surgery.Extensions.Testing.AutoFixtures.csproj
  src/Testing.Fixtures/ITestFixtureBuilder.cs
  src/Testing.Fixtures/TestFixtureBuilderExtensions.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorData.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixtureAttributeUsage_WhenGenerate_ThenGeneratedAutoFixture_fe52e10a1e7987b0#AutoFixture.verified.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixtureAttributeUsage_WhenGenerate_ThenGeneratedAutoFixture_fe52e10a1e7987b0.verified.txt
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixture_WhenGenerate_ThenShouldGenerateAutoFixtureAttribute#AutoFixtureAttribute.verified.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixture_WhenGenerate_ThenShouldGenerateAutoFixtureAttribute.verified.txt
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixture_WhenGenerate_ThenShouldGenerateFixtureBuilderExtensions#BuilderInterface.verified.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixture_WhenGenerate_ThenShouldGenerateFixtureBuilderExtensions.verified.txt
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenFakeItEasy_WhenGenerate_ThenGeneratedAutoFixtureWithFakes_fe52e10a1e7987b0#AutoFixture.verified.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenFakeItEasy_WhenGenerate_ThenGeneratedAutoFixtureWithFakes_fe52e10a1e7987b0.verified.txt
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenNSubstitute_WhenGenerate_ThenGeneratedAutoFixtureWithFakes_fe52e10a1e7987b0#AutoFixture.verified.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenNSubstitute_WhenGenerate_ThenGeneratedAutoFixtureWithFakes_fe52e10a1e7987b0.verified.txt
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.cs
  test/Testing.AutoFixtures.Tests/ModuleInitializer.cs
  test/Testing.AutoFixtures.Tests/Rocket.Surgery.Extensions.Testing.AutoFixtures.Tests.csproj
  test/Testing.Fixtures.Tests/TestFixtureBuilderExtensionTests.cs
  test/Testing.Tests/Fake/AutoFakeEnumerableTests.cs
  test/Testing.Tests/Fake/AutoFakePopulateTests.cs
  test/Testing.Tests/Fake/AutoFakeTestTests.cs
  test/Testing.Tests/LoggerTestTests.cs
  test/Testing.Tests/Mock/AutoMockEnumerableTests.cs
  test/Testing.Tests/Mock/AutoMockPopulateTests.cs
  test/Testing.Tests/Mock/AutoMockTestTests.cs
  test/Testing.Tests/Substitute/AutoSubstituteEnumerableTests.cs
  test/Testing.Tests/Substitute/AutoSubstitutePopulateTests.cs
  test/Testing.Tests/Substitute/AutoSubstituteTestTests.cs
  test/Testing.Tests/XUnitExtensionsTests.cs
Labels: :rocket: feature

#1142 bug: AutoFixture package not generating source
  src/Testing.AutoFixtures/Rocket.Surgery.Extensions.Testing.AutoFixtures.csproj
Labels: :lady_beetle: bug

#1148 bug: AutoFixture attribute not generating in target assembly
  src/Testing.AutoFixtures/Attribute.cs
  src/Testing.AutoFixtures/AutoTestFixtureBuilderGenerator.cs
  src/Testing.AutoFixtures/README.md
  src/Testing.AutoFixtures/Rocket.Surgery.Extensions.Testing.AutoFixtures.csproj
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixtureAttributeUsage_WhenGenerate_ThenGeneratedAutoFixture_fe52e10a1e7987b0#Authenticator.AutoFixture.g.verified.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixture_WhenGenerate_ThenShouldGenerateAutoFixtureAttribute#AutoFixtureAttribute.g.verified.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixture_WhenGenerate_ThenShouldGenerateFixtureBuilderExtensions#BuilderInterface.g.verified.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenFakeItEasy_WhenGenerate_ThenGeneratedAutoFixtureWithFakes_fe52e10a1e7987b0#Authenticator.AutoFixture.g.verified.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenNSubstitute_WhenGenerate_ThenGeneratedAutoFixtureWithFakes_fe52e10a1e7987b0#Authenticator.AutoFixture.g.verified.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.cs
Labels: :lady_beetle: bug

#1159 bug: no support for constructors with parameter arrays
  src/Testing.AutoFixtures/AutoFixtureGenerator+StaticGenerator.cs
  src/Testing.AutoFixtures/AutoFixtureGenerator.cs
  src/Testing.AutoFixtures/Diagnostics.cs
  src/Testing.AutoFixtures/Methods.cs
  src/Testing.AutoFixtures/README.md
  src/Testing.AutoFixtures/Rocket.Surgery.Extensions.Testing.AutoFixtures.csproj
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorData.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixtureAttributeUsage_WhenGenerate_ThenGeneratedAutoFixture_05a83d5a8ca44dd1#Authenticator.AutoFixture.g.verified.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixtureAttributeUsage_WhenGenerate_ThenGeneratedAutoFixture_05a83d5a8ca44dd1.verified.txt
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixture_WhenGenerate_ThenShouldGenerateAutoFixtureAttribute#AutoFixtureAttribute.g.verified.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenDeckSource_WhenGenerate_ThenGeneratedAutoFixtureWithFakes_08f2026ad4e1993a#Deck.AutoFixture.g.verified.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenDeckSource_WhenGenerate_ThenGeneratedAutoFixtureWithFakes_08f2026ad4e1993a.verified.txt
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenDeckSource_WhenGenerate_ThenGeneratedAutoFixtureWithFakes_1729d8a988210723.verified.txt
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenDeckSource_WhenGenerate_ThenGeneratedAutoFixtureWithFakes_8f021240ae07a7f8.verified.txt
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenDeckSource_WhenGenerate_ThenGeneratedAutoFixtureWithFakes_999b4b95376f0cb1#Deck.AutoFixture.g.verified.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenDeckSource_WhenGenerate_ThenGeneratedAutoFixture_16325dfd331fff7c#Deck.AutoFixture.g.verified.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenDeckSource_WhenGenerate_ThenGeneratedAutoFixture_16325dfd331fff7c.verified.txt
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenDeckSource_WhenGenerate_ThenGeneratedAutoFixture_6c0088193547a711#Deck.AutoFixture.g.verified.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenDeckSource_WhenGenerate_ThenGeneratedAutoFixture_6c0088193547a711.verified.txt
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenDeckSource_WhenGenerate_ThenGeneratedAutoFixture_705558077183c21b#Deck.AutoFixture.g.verified.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenDeckSource_WhenGenerate_ThenGeneratedAutoFixture_705558077183c21b.verified.txt
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenDeckSource_WhenGenerate_ThenGeneratedAutoFixture_c94c4982e88eb313#Deck.AutoFixture.g.verified.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenDeckSource_WhenGenerate_ThenGeneratedAutoFixture_c94c4982e88eb313.verified.txt
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenFakeItEasy_WhenGenerate_ThenGeneratedAutoFixtureWithFakes_05a83d5a8ca44dd1#Authenticator.AutoFixture.g.verified.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenFakeItEasy_WhenGenerate_ThenGeneratedAutoFixtureWithFakes_05a83d5a8ca44dd1.verified.txt
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenNSubstitute_WhenGenerate_ThenGeneratedAutoFixtureWithFakes_05a83d5a8ca44dd1#Authenticator.AutoFixture.g.verified.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenNSubstitute_WhenGenerate_ThenGeneratedAutoFixtureWithFakes_05a83d5a8ca44dd1.verified.txt
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenSeparateNamespace_WhenGenerate_ThenGeneratedAutoFixtureWithFakes_24a18d6d15caf532#Authenticator.AutoFixture.g.verified.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenSeparateNamespace_WhenGenerate_ThenGeneratedAutoFixtureWithFakes_24a18d6d15caf532.verified.txt
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenSeparateNamespace_WhenGenerate_ThenGeneratedAutoFixtureWithFakes_34ed92282567eb33#Authenticator.AutoFixture.g.verified.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenSeparateNamespace_WhenGenerate_ThenGeneratedAutoFixtureWithFakes_34ed92282567eb33.verified.txt
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.cs
Labels: :lady_beetle: bug

#1162 fix: generated source in the wrong namespace
  src/Testing.AutoFixtures/AutoFixtureGenerator+StaticGenerator.cs
  src/Testing.AutoFixtures/AutoFixtureGenerator.cs
Labels: :lady_beetle: bug

#1167 fixed a case where if the output file started with the name of the in…
  src/Testing.SourceGenerators/Customizers.cs
  src/Testing.SourceGenerators/VerifyGeneratorTextContext.cs
  test/Testing.Tests/Generators/GeneratorContextTests.Should_Not_Filter_Ouputs_Named_After_Input#Input0.verified.cs
  test/Testing.Tests/Generators/GeneratorContextTests.Should_Not_Filter_Ouputs_Named_After_Input#Input0_ouput.g.verified.cs
  test/Testing.Tests/Generators/GeneratorContextTests.Should_Not_Filter_Ouputs_Named_After_Input.verified.txt
  test/Testing.Tests/Generators/GeneratorContextTests.cs
  test/Testing.Tests/Generators/MySourceGenerator.cs
Labels: :lady_beetle: bug

#1173 fix: generate the generic type parameter
  src/Testing.AutoFixtures/AutoFixtureGenerator+StaticGenerator.cs
  src/Testing.AutoFixtures/AutoFixtureGenerator.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixtureAttributeUsage_WhenGenerate_ThenGeneratedAutoFixture_8dd3a84350cd8ade#Authenticator.AutoFixture.g.verified.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenDeckSource_WhenGenerate_ThenGeneratedAutoFixture_619350127f939922#Deck.AutoFixture.g.verified.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenFakeItEasy_WhenGenerate_ThenGeneratedAutoFixtureWithFakes_8dd3a84350cd8ade#Authenticator.AutoFixture.g.verified.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenNSubstitute_WhenGenerate_ThenGeneratedAutoFixtureWithFakes_8dd3a84350cd8ade#Authenticator.AutoFixture.g.verified.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenSeparateNamespace_WhenGenerate_ThenGeneratedAutoFixtureWithFakes_530b28ef607437fa#Authenticator.AutoFixture.g.verified.cs
Labels: :lady_beetle: bug

#1177 fix: same type generating multiple times
  src/Testing.AutoFixtures/AutoFixtureGenerator+StaticGenerator.cs
  src/Testing.AutoFixtures/AutoFixtureGenerator.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.cs
  test/Testing.AutoFixtures.Tests/DuplicateConstructorParameterData.cs
  test/Testing.AutoFixtures.Tests/DuplicateConstructorParameterTests.GivenMultipleConstructorParameters_WhenGenerate_ThenGeneratedAutoFixture_0d621e33ceaec4b5#DuplicateConstructorParameter.AutoFixture.g.verified.cs
  test/Testing.AutoFixtures.Tests/DuplicateConstructorParameterTests.GivenMultipleConstructorParameters_WhenGenerate_ThenGeneratedAutoFixture_0d621e33ceaec4b5.verified.txt
  test/Testing.AutoFixtures.Tests/DuplicateConstructorParameterTests.GivenMultipleConstructorParameters_WhenGenerate_ThenGeneratedAutoFixture_54b34fcc5f0e74ea#DuplicateConstructorParameter.AutoFixture.g.verified.cs
  test/Testing.AutoFixtures.Tests/DuplicateConstructorParameterTests.GivenMultipleConstructorParameters_WhenGenerate_ThenGeneratedAutoFixture_54b34fcc5f0e74ea.verified.txt
  test/Testing.AutoFixtures.Tests/DuplicateConstructorParameterTests.GivenMultipleConstructorParameters_WhenGenerate_ThenGeneratedAutoFixture_7c4a6f2b7d0faead.verified.txt
  test/Testing.AutoFixtures.Tests/DuplicateConstructorParameterTests.GivenMultipleConstructorParameters_WhenGenerate_ThenGeneratedAutoFixture_f300dbca6c3d0b47#Authenticator.AutoFixture.g.verified.cs
  test/Testing.AutoFixtures.Tests/DuplicateConstructorParameterTests.GivenMultipleConstructorParameters_WhenGenerate_ThenGeneratedAutoFixture_f300dbca6c3d0b47.verified.txt
  test/Testing.AutoFixtures.Tests/DuplicateConstructorParameterTests.GivenMultiplePrimitiveConstructorParameters_WhenGenerate_ThenGeneratedByParameterName_0d621e33ceaec4b5#DuplicateConstructorParameter.AutoFixture.g.verified.cs
  test/Testing.AutoFixtures.Tests/DuplicateConstructorParameterTests.GivenMultiplePrimitiveConstructorParameters_WhenGenerate_ThenGeneratedByParameterName_0d621e33ceaec4b5.verified.txt
  test/Testing.AutoFixtures.Tests/DuplicateConstructorParameterTests.cs
Labels: :lady_beetle: bug

#1178 fix: usings missing from AutoFixtureBase
  src/Testing.AutoFixtures/AutoFixtureBase.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixture_WhenGenerate_ThenShouldGenerateAutoFixtureBase#AutoFixtureBase.g.verified.cs
Labels: :lady_beetle: bug

#1181 chore: clean tests so adding member data is the way
  src/Testing.SourceGenerators/GeneratorTestContext.cs
  src/Testing.SourceGenerators/GeneratorTestContextBuilder.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorData.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixtureAttribute_WhenGenerate_ThenGeneratesAutoFixture_0dcb461dbd68532f#Authenticator.AutoFixture.g.verified.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixtureAttribute_WhenGenerate_ThenGeneratesAutoFixture_0dcb461dbd68532f.verified.txt
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixtureAttribute_WhenGenerate_ThenGeneratesAutoFixture_0e65142380ceba0c#DuplicateConstructorParameter.AutoFixture.g.verified.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixtureAttribute_WhenGenerate_ThenGeneratesAutoFixture_0e65142380ceba0c.verified.txt
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixtureAttribute_WhenGenerate_ThenGeneratesAutoFixture_2b8877a7db13124d#Authenticator.AutoFixture.g.verified.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixtureAttribute_WhenGenerate_ThenGeneratesAutoFixture_2b8877a7db13124d.verified.txt
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixtureAttribute_WhenGenerate_ThenGeneratesAutoFixture_3585358834870949#Authenticator.AutoFixture.g.verified.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixtureAttribute_WhenGenerate_ThenGeneratesAutoFixture_3585358834870949.verified.txt
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixtureAttribute_WhenGenerate_ThenGeneratesAutoFixture_3d7494a3a6ed5e27#DuplicateConstructorParameter.AutoFixture.g.verified.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixtureAttribute_WhenGenerate_ThenGeneratesAutoFixture_3d7494a3a6ed5e27.verified.txt
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixtureAttribute_WhenGenerate_ThenGeneratesAutoFixture_4df3a350b2f7c9e9#DuplicateConstructorParameter.AutoFixture.g.verified.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixtureAttribute_WhenGenerate_ThenGeneratesAutoFixture_4df3a350b2f7c9e9.verified.txt
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixtureAttribute_WhenGenerate_ThenGeneratesAutoFixture_4fd3c677b14638a0#DuplicateConstructorParameter.AutoFixture.g.verified.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixtureAttribute_WhenGenerate_ThenGeneratesAutoFixture_4fd3c677b14638a0.verified.txt
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixtureAttribute_WhenGenerate_ThenGeneratesAutoFixture_580cb09c8245eef0#Authenticator.AutoFixture.g.verified.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixtureAttribute_WhenGenerate_ThenGeneratesAutoFixture_580cb09c8245eef0.verified.txt
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixtureAttribute_WhenGenerate_ThenGeneratesAutoFixture_749a3742ebdbb25c#DuplicateConstructorParameter.AutoFixture.g.verified.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixtureAttribute_WhenGenerate_ThenGeneratesAutoFixture_749a3742ebdbb25c.verified.txt
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixtureAttribute_WhenGenerate_ThenGeneratesAutoFixture_7dc11407328bba0b#Authenticator.AutoFixture.g.verified.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixtureAttribute_WhenGenerate_ThenGeneratesAutoFixture_7dc11407328bba0b.verified.txt
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixtureAttribute_WhenGenerate_ThenGeneratesAutoFixture_7e84353e9214cce0#DuplicateConstructorParameter.AutoFixture.g.verified.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixtureAttribute_WhenGenerate_ThenGeneratesAutoFixture_7e84353e9214cce0.verified.txt
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixtureAttribute_WhenGenerate_ThenGeneratesAutoFixture_aea34916e4f9cc26#Authenticator.AutoFixture.g.verified.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixtureAttribute_WhenGenerate_ThenGeneratesAutoFixture_aea34916e4f9cc26.verified.txt
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixtureAttribute_WhenGenerate_ThenGeneratesAutoFixture_b54046d829452c9b#DuplicateConstructorParameter.AutoFixture.g.verified.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixtureAttribute_WhenGenerate_ThenGeneratesAutoFixture_b54046d829452c9b.verified.txt
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixtureAttribute_WhenGenerate_ThenGeneratesAutoFixture_ce0a1fc920a745dc#DuplicateConstructorParameter.AutoFixture.g.verified.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixtureAttribute_WhenGenerate_ThenGeneratesAutoFixture_ce0a1fc920a745dc.verified.txt
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixtureAttribute_WhenGenerate_ThenGeneratesAutoFixture_d2c5bb79949d911d#Authenticator.AutoFixture.g.verified.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixtureAttribute_WhenGenerate_ThenGeneratesAutoFixture_d2c5bb79949d911d.verified.txt
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixtureAttribute_WhenGenerate_ThenGeneratesAutoFixture_d86ed52f1d643acd#DuplicateConstructorParameter.AutoFixture.g.verified.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixtureAttribute_WhenGenerate_ThenGeneratesAutoFixture_d86ed52f1d643acd.verified.txt
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixtureAttribute_WhenGenerate_ThenGeneratesAutoFixture_d9329d742967ab74#Authenticator.AutoFixture.g.verified.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixtureAttribute_WhenGenerate_ThenGeneratesAutoFixture_d9329d742967ab74.verified.txt
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixtureAttribute_WhenGenerate_ThenGeneratesAutoFixture_f4eb0890b68033f9#Authenticator.AutoFixture.g.verified.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixtureAttribute_WhenGenerate_ThenGeneratesAutoFixture_f4eb0890b68033f9.verified.txt
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenConstructorWithEnumerable_WhenGenerate_ThenGeneratesAutoFixture_1a63e17a17607b3b#Deck.AutoFixture.g.verified.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenConstructorWithEnumerable_WhenGenerate_ThenGeneratesAutoFixture_1a63e17a17607b3b.verified.txt
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenConstructorWithEnumerable_WhenGenerate_ThenGeneratesAutoFixture_21844e6efed4eac9#Deck.AutoFixture.g.verified.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenConstructorWithEnumerable_WhenGenerate_ThenGeneratesAutoFixture_21844e6efed4eac9.verified.txt
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenConstructorWithEnumerable_WhenGenerate_ThenGeneratesAutoFixture_2ca9c52804670116#Deck.AutoFixture.g.verified.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenConstructorWithEnumerable_WhenGenerate_ThenGeneratesAutoFixture_2ca9c52804670116.verified.txt
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenConstructorWithEnumerable_WhenGenerate_ThenGeneratesAutoFixture_705b309cf7c53a38#Deck.AutoFixture.g.verified.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenConstructorWithEnumerable_WhenGenerate_ThenGeneratesAutoFixture_705b309cf7c53a38.verified.txt
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenConstructorWithEnumerable_WhenGenerate_ThenGeneratesAutoFixture_d66714739e000a9d#Deck.AutoFixture.g.verified.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenConstructorWithEnumerable_WhenGenerate_ThenGeneratesAutoFixture_d66714739e000a9d.verified.txt
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureSourceData.cs
  test/Testing.AutoFixtures.Tests/DuplicateConstructorParameterData.cs
  test/Testing.AutoFixtures.Tests/DuplicateConstructorParameterTests.GivenMultipleConstructorParameters_WhenGenerate_ThenGeneratedAutoFixture_54b34fcc5f0e74ea#DuplicateConstructorParameter.AutoFixture.g.verified.cs
  test/Testing.AutoFixtures.Tests/DuplicateConstructorParameterTests.GivenMultipleConstructorParameters_WhenGenerate_ThenGeneratedAutoFixture_54b34fcc5f0e74ea.verified.txt
  test/Testing.AutoFixtures.Tests/DuplicateConstructorParameterTests.GivenMultipleConstructorParameters_WhenGenerate_ThenGeneratedAutoFixture_7c4a6f2b7d0faead.verified.txt
  test/Testing.AutoFixtures.Tests/DuplicateConstructorParameterTests.GivenMultipleConstructorParameters_WhenGenerate_ThenGeneratedAutoFixture_f300dbca6c3d0b47#Authenticator.AutoFixture.g.verified.cs
  test/Testing.AutoFixtures.Tests/DuplicateConstructorParameterTests.GivenMultipleConstructorParameters_WhenGenerate_ThenGeneratedAutoFixture_f300dbca6c3d0b47.verified.txt
  test/Testing.AutoFixtures.Tests/DuplicateConstructorParameterTests.cs
  test/Testing.AutoFixtures.Tests/ParameterArraySourceData.cs
Labels: :hammer: chore

#1185 chore: fix xUnit1042
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorData.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixtureAttribute_WhenGenerate_ThenGeneratesAutoFixture_5f7b6e7d60aa65e8#Authenticator.AutoFixture.g.verified.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixtureAttribute_WhenGenerate_ThenGeneratesAutoFixture_5f7b6e7d60aa65e8.verified.txt
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixtureAttribute_WhenGenerate_ThenGeneratesAutoFixture_f39eb412a864d4a9#Authenticator.AutoFixture.g.verified.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixtureAttribute_WhenGenerate_ThenGeneratesAutoFixture_f39eb412a864d4a9.verified.txt
  test/Testing.AutoFixtures.Tests/AutoFixtureSourceData.cs
  test/Testing.AutoFixtures.Tests/DuplicateConstructorParameterData.cs
  test/Testing.AutoFixtures.Tests/ParameterArraySourceData.cs
  test/Testing.AutoFixtures.Tests/ValueTypeSourceData.cs
Labels: :hammer: chore
