Repository RocketSurgeonsGuild/Testing, pull requests merged in 2024-04, with the labels that each got.

#1186 feature: add version to generated source
  src/Testing.AutoFixtures/Attribute.cs
  src/Testing.AutoFixtures/AutoFixtureGenerator.cs
  src/Testing.AutoFixtures/AutoFixtures.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.cs
Labels: :rocket: feature

#1189 feature: adding support for non abstract reference types
  src/Testing.AutoFixtures/AutoFixtureGenerator+StaticGenerator.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixtureAttribute_WhenGenerate_ThenGeneratesAutoFixture_1d9a2140d1279905#NonAbstractReferenceType.AutoFixture.g.verified.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixtureAttribute_WhenGenerate_ThenGeneratesAutoFixture_1d9a2140d1279905.verified.txt
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixtureAttribute_WhenGenerate_ThenGeneratesAutoFixture_2d060ee926a50805#NonAbstractReferenceType.AutoFixture.g.verified.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixtureAttribute_WhenGenerate_ThenGeneratesAutoFixture_2d060ee926a50805.verified.txt
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixtureAttribute_WhenGenerate_ThenGeneratesAutoFixture_7ed0016341a5d28e#NonAbstractReferenceType.AutoFixture.g.verified.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixtureAttribute_WhenGenerate_ThenGeneratesAutoFixture_7ed0016341a5d28e.verified.txt
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixtureAttribute_WhenGenerate_ThenGeneratesAutoFixture_f2ea5acbb94bfeeb#NonAbstractReferenceType.AutoFixture.g.verified.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.GivenAutoFixtureAttribute_WhenGenerate_ThenGeneratesAutoFixture_f2ea5acbb94bfeeb.verified.txt
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.cs
  test/Testing.AutoFixtures.Tests/NonAbstractReferenceTypeData.cs
Labels: :fire: enhancement

#1193 fix: No constructor no source being generated
  src/Testing.AutoFixtures/AutoFixtureGenerator+StaticGenerator.cs
  src/Testing.AutoFixtures/AutoFixtureGenerator.cs
  src/Testing.AutoFixtures/Diagnostics.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureGeneratorTests.cs
  test/Testing.AutoFixtures.Tests/AutoFixtureSourceData.cs
  test/Testing.AutoFixtures.Tests/ConstructorlessFixturesData.cs
Labels: :lady_beetle: bug

#1230 Updating to dryioc preview
  Directory.Packages.props
  GitVersion.yml
  src/Testing.FakeItEasy/AutoFake.cs
  src/Testing.FakeItEasy/AutoFakeTest.cs
  src/Testing.Moq/AutoMock.cs
  src/Testing.Moq/AutoMockTest.cs
  src/Testing.NSubstitute/AutoSubstitute.cs
  src/Testing.NSubstitute/AutoSubstituteTest.cs
Labels: :boom: breaking change

#1231 enable msdi rules
  src/Testing.FakeItEasy/AutoFakeTest.cs
  src/Testing.Moq/AutoMockTest.cs
  src/Testing.NSubstitute/AutoSubstituteTest.cs
Labels: :lady_beetle: bug
